#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/a0bf3cc5-f2df-4e80-81c9-34fc06660c4a 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool pushButtonState;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
  ArduinoCloud.update();
  
  if (pushButtonState) {blinkName();}
  
}

void blinkName() {
  // L
  blinkDot();
  blinkDash();
  blinkDot();
  blinkDot();
  delay(1500); 
  
  // O
  blinkDash();
  blinkDash();
  blinkDash();
  delay(1500); 
  
  // G
  blinkDash();
  blinkDash();
  blinkDot();
  delay(1500); 
  
  // A
  blinkDot();
  blinkDash();
  delay(1500); 
  
  // N
  blinkDash();
  blinkDot();
}
  
void blinkDot() {
  digitalWrite(LED_BUILTIN, HIGH);
  delay(500);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
}

void blinkDash() {
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1500);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
}

/*
  Since PushButtonState is READ_WRITE variable, onPushButtonStateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPushButtonStateChange()  {
}